export const kids = [{
        id: "kid01",
        title: "School blezer school sweater lene k liye sampark kare",
        price: "600",
        image: "https://apollo-singapore.akamaized.net/v1/files/hlzcsj48a9bt3-IN/image;s=780x0;q=60",
        date: "Yesterday",
        address: "New Transport Nagar, GIDA Gorakhpur, Uttar Pradesh",
        featured: "FEATURED",
        seller: "Surya",
        location: "Uttar pradesh",
        category: "kids",
        desc: "Blezer sweater etc",

    },
    {
        id: "kid02",
        title: "Brnded quality Kidsware in bulk available",
        price: "250",
        image: "https://apollo-singapore.akamaized.net/v1/files/f804w6gbm2gg3-IN/image;s=780x0;q=60",
        date: "Oct24",
        address: "Bolarum, Hyderabad, Telangana",
        featured: "FEATURED",
        seller: "Madhu P",
        location: "Uttar pradesh",
        category: "kids",
        desc: "Kids wear (frocks,leggings, shorts, skirts etc..) available in bulk."
    },
    {
        id: "kid03",
        title: "Laddu Gopal dress best deging",
        price: "150",
        image: "https://apollo-singapore.akamaized.net/v1/files/krj6ny1t771b2-IN/image;s=640x0;q=60",
        date: "Today",
        address: "Islam Nagar, Khatauli, Uttar Pradesh",
        featured: "FEATURED",
        seller: "Sangita Soam",
        location: "Uttar pradesh",
        category: "kids",
        desc: "Laddu gopal drees"
    },
    {
        id: "kid04",
        title: "Huggies wonder Pants Diapers ",
        price: "499",
        image: "https://apollo-singapore.akamaized.net/v1/files/ifruupphlqbi3-IN/image;s=640x0;q=60",
        date: "Today",
        address: "Goregaon West, Mumbai, Maharashtra",
        featured: "FEATURED",
        seller: "Rupesh",
        location: "Uttar pradesh",
        category: "kids",
        desc: "Huggies wonder Pants Diapers 42 Pieces L size, suitable for kids with weight between 9-14KG"
    },
]
export const fresh = [{
        id: "fresh01",
        title: "Honda Amaze (2019)",
        price: "",
        image: "https://apollo-singapore.akamaized.net/v1/files/ve7t6jjz3nbd1-IN/image;s=780x0;q=60",
        date: "05-SEP-22",
        address: "Noida Extention Sector 4, Noida",
        location: "Uttar pradesh",
        category: "car",
        desc: " good condition",
        featured: "FEATURED",
    },
    {
        id: "fresh02",
        title: "3 Bds - 2 Ba - 1280 ft2",
        price: "55,00,000",
        image: "https://apollo-singapore.akamaized.net/v1/files/qy0cyb5swj1j2-IN/image;s=780x0;q=60",
        date: "Oct 12",
        address: "Mythri Nagar, Hyderabad, Telangana",
        location: "Uttar pradesh",
        category: "house",
        desc: " price is slightly negotiable~}",
        featured: "FEATURED",
    },
    {
        id: "fresh03",
        title: "HONDA UNICORN 2017",
        price: "63,000",
        image: "https://apollo-singapore.akamaized.net/v1/files/hfbhguha58951-IN/image;s=780x0;q=60",
        date: "Today",
        address: "Mythri Nagar, Hyderabad, Telangana",
        location: "Hyderabad",
        category: "Bike",
        desc: " price is slightly negotiable~}",
        featured: "FEATURED",
    },
    {
        id: "fresh04",
        title: "YAMAHA R15 V3 2022 ",
        price: "1,62,000",
        image: "https://apollo-singapore.akamaized.net/v1/files/hfbhguha58951-IN/image;s=780x0;q=60",
        date: "Oct 12",
        address: "Mythri Nagar, Hyderabad, Telangana",
        location: "Uttar pradesh",
        category: "house",
        desc: " price is slightly negotiable~}",
        featured: "FEATURED",
    },
    {
        id: "fresh05",
        title: "35 seater office ",
        price: "1,20,000",
        image: "https://apollo-singapore.akamaized.net/v1/files/bmz207e00th3-IN/image;s=780x0;q=60",
        date: "Today",
        address: "Madhapur, Hyderabad, Telangana",
        location: "Telangana",
        category: "rent",
        desc: " Plug and play office space rent in Madhapur. 2cabin 1 meeting room more details contact me Lakshman agent",
        featured: "FEATURED",
    },
    {
        id: "fresh08",
        title: "2 Bds - 2 Ba - 1330 ft2",
        price: "75,79,000",
        image: "https://apollo-singapore.akamaized.net/v1/files/ts8vum9cg2ka2-IN/image;s=780x0;q=60",
        date: "Today",
        address: "Qutbullapur, Hyderabad, Telangana",
        location: "Telangana",
        category: "rent",
        desc: " Gated community 2 bhk flats at miyapur",
        featured: "FEATURED",
    },
    {
        id: "fresh06",
        title: "TODAY PRICE 43 SMART TV  ",
        price: "9,500",
        image: "https://apollo-singapore.akamaized.net/v1/files/twe0kfrh7u2f3-IN/image;s=780x0;q=60",
        date: "Today",
        address: "Erragadda, Hyderabad, Telangana",
        location: "Telangana",
        category: "electronics",
        desc: " GUARANTEE 1YEAR",
        featured: "FEATURED",
    },
    {
        id: "fresh07",
        title: "Mi 11x phone bill 128 GB 6 Ram ",
        price: "6,000",
        image: "https://apollo-singapore.akamaized.net/v1/files/0mc8na9wltsn3-IN/image;s=1080x1080",
        date: "Today",
        address: "Madhapur, Hyderabad, Telangana",
        location: "Telangana",
        category: "mobiles",
        desc: " Mobile touch is not working",
        featured: "FEATURED",
    },

]